routines:
  recoleccion:
    - name: "Home"
      pose: {x: 0.0, y: 0.0, z: 0.406, roll: 0.0, pitch: 0.0, yaw: 3.142}
      gripper: "open"
    - name: "Approach"
      pose: {x: 0.100, y: 0.0, z: 0.140, roll: 3.142, pitch: 0.195, yaw: 0.000}
    - name: "Lift"
      pose: {x: 0.099, y: 0.0, z: 0.045, roll: 3.142, pitch: 0.194, yaw: 0.000}
      gripper: "close"
    - name: "Approach"
      pose: {x: 0.100, y: 0.0, z: 0.140, roll: 3.142, pitch: 0.195, yaw: 0.000}

  cilindro:
    - name: "Home"
      pose: {x: 0.0, y: 0.0, z: 0.406, roll: 0.0, pitch: 0.0, yaw: 3.142}
      gripper: "open"
    - name: "Approach"
      pose: {x: 0.100, y: 0.0, z: 0.140, roll: 3.142, pitch: 0.195, yaw: 0.000}
    - name: "Lift"
      pose: {x: 0.099, y: 0.0, z: 0.045, roll: 3.142, pitch: 0.194, yaw: 0.000}
      gripper: "close"
    - name: "Approach"
      pose: {x: 0.100, y: 0.0, z: 0.140, roll: 3.142, pitch: 0.195, yaw: 0.000}
    - name: "Place Cilindro"
      pose: {x: 0.184, y: 0.085, z: 0.102, roll: 3.142, pitch: -0.431, yaw: 0.433}
      gripper: "open"
    - name: "Home"
      pose: {x: 0.0, y: 0.0, z: 0.406, roll: 0.0, pitch: 0.0, yaw: 3.142}

  cubo:
    - name: "Home"
      pose: {x: 0.0, y: 0.0, z: 0.406, roll: 0.0, pitch: 0.0, yaw: 3.142}
      gripper: "open"
    - name: "Approach"
      pose: {x: 0.100, y: 0.0, z: 0.140, roll: 3.142, pitch: 0.195, yaw: 0.000}
    - name: "Lift"
      pose: {x: 0.099, y: 0.0, z: 0.045, roll: 3.142, pitch: 0.194, yaw: 0.000}
      gripper: "close"
    - name: "Approach"
      pose: {x: 0.100, y: 0.0, z: 0.140, roll: 3.142, pitch: 0.195, yaw: 0.000}
    - name: "Place Cubo"
      pose: {x: -0.008, y: 0.118, z: 0.128, roll: 3.142, pitch: 0.087, yaw: 1.635}
      gripper: "open"
    - name: "Home"
      pose: {x: 0.0, y: 0.0, z: 0.406, roll: 0.0, pitch: 0.0, yaw: 3.142}

  rectangulo:
    - name: "Home"
      pose: {x: 0.0, y: 0.0, z: 0.406, roll: 0.0, pitch: 0.0, yaw: 3.142}
      gripper: "open"
    - name: "Approach"
      pose: {x: 0.100, y: 0.0, z: 0.140, roll: 3.142, pitch: 0.195, yaw: 0.000}
    - name: "Lift"
      pose: {x: 0.099, y: 0.0, z: 0.045, roll: 3.142, pitch: 0.194, yaw: 0.000}
      gripper: "close"
    - name: "Approach"
      pose: {x: 0.100, y: 0.0, z: 0.140, roll: 3.142, pitch: 0.195, yaw: 0.000}
    - name: "Place Rectangulo"
      pose: {x: -0.009, y: -0.117, z: 0.128, roll: 3.142, pitch: 0.087, yaw: -1.650}
      gripper: "open"
    - name: "Home"
      pose: {x: 0.0, y: 0.0, z: 0.406, roll: 0.0, pitch: 0.0, yaw: 3.142}

  pentagono:
    - name: "Home"
      pose: {x: 0.0, y: 0.0, z: 0.406, roll: 0.0, pitch: 0.0, yaw: 3.142}
      gripper: "open"
    - name: "Approach"
      pose: {x: 0.100, y: 0.0, z: 0.140, roll: 3.142, pitch: 0.195, yaw: 0.000}
    - name: "Lift"
      pose: {x: 0.099, y: 0.0, z: 0.045, roll: 3.142, pitch: 0.194, yaw: 0.000}
      gripper: "close"
    - name: "Approach"
      pose: {x: 0.100, y: 0.0, z: 0.140, roll: 3.142, pitch: 0.195, yaw: 0.000}
    - name: "Place Pentagono"
      pose: {x: 0.198, y: -0.092, z: 0.125, roll: 3.142, pitch: -0.616, yaw: -0.433}
      gripper: "open"
    - name: "Home"
      pose: {x: 0.0, y: 0.0, z: 0.406, roll: 0.0, pitch: 0.0, yaw: 3.142}
