# Archivo de configuración para las poses del PhantomX Pincher
#
# Unidades:
#   - Metros para posición (x, y, z)
#   - Radianes para orientación (roll, pitch, yaw)

poses:
  # Posición segura/inicial (pose válida y alcanzable)
  home:
    x: 0.100
    y: 0.000
    z: 0.140
    roll: 3.142
    pitch: 0.0
    yaw: 0.0

  # Zona donde aparecen los objetos (pose alcanzable para pick)
  recoleccion:
    x: 0.100
    y: 0.000
    z: 0.040
    roll: 3.142
    pitch: -0.007
    yaw: 0.0

  # Destinos para cada figura/color (poses alcanzables)
  caneca_roja:  # Cubo
    x: -0.014
    y: 0.127
    z: 0.070
    roll: 3.142
    pitch: 0.014
    yaw: 1.680

  caneca_verde:  # Cilindro
    x: 0.186
    y: 0.086
    z: 0.065
    roll: 3.142
    pitch: -0.299
    yaw: 0.433

  caneca_azul:  # Pentágono
    x: 0.190
    y: -0.098
    z: 0.065
    roll: 3.142
    pitch: -0.391
    yaw: -0.477

  caneca_amarilla:  # Rectángulo
    x: -0.007
    y: -0.113
    z: 0.064
    roll: 3.142
    pitch: -0.062
    yaw: -1.635

