# Archivo de configuración para las poses del PhantomX Pincher
#
# Unidades:
#   - Metros para posición (x, y, z)
#   - Radianes para orientación (roll, pitch, yaw)

poses:
  # Posición HOME lejana/segura (tu paso 1)
  home:
    x: 0.050
    y: 0.000
    z: 0.400
    roll: 0.0
    pitch: 0.0
    yaw: -3.142

  # Aproximación a recolección (tu paso 2)
  recoleccion_1:
    x: 0.128
    y: 0.000
    z: 0.100
    roll: 3.142
    pitch: 0.0
    yaw: 0.0

  # Recolección baja (tu paso 3)
  recoleccion_2:
    x: 0.110
    y: 0.000
    z: 0.055
    roll: 3.142
    pitch: 0.0
    yaw: 0.0

  # Alias para compatibilidad (no lo usa el clasificador directamente)
  recoleccion:
    x: 0.110
    y: 0.000
    z: 0.055
    roll: 3.142
    pitch: 0.0
    yaw: 0.0

  # Destinos para cada figura/color, usando TUS poses
  caneca_roja:  # Cubo
    x: -0.009
    y: 0.117
    z: 0.104
    roll: 3.142
    pitch: -0.074
    yaw: 1.650

  caneca_verde:  # Cilindro
    x: 0.196
    y: 0.091
    z: 0.179
    roll: 3.142
    pitch: -0.957
    yaw: 0.433

  caneca_azul:  # Pentágono
    x: 0.192
    y: -0.088
    z: 0.184
    roll: 3.142
    pitch: -1.105
    yaw: -0.433

  caneca_amarilla:  # Rectángulo
    x: -0.010
    y: -0.122
    z: 0.109
    roll: 3.142
    pitch: 0.087
    yaw: -1.650
