robot_description_kinematics:
  arm:
    kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
    kinematics_solver_search_resolution: 0.01
    kinematics_solver_timeout: 1.0      # aqu√≠ puedes subir a 1.0
    position_only_ik: true
    # opcional:
    kinematics_solver_attempts: 5