robot_description_kinematics:
  arm:
    # En Humble el plugin LMA no está disponible por defecto.
    # Volvemos al solver estándar basado en KDL, que sí está instalado.
    kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
    kinematics_solver_search_resolution: 0.005
    kinematics_solver_timeout: 0.5
    position_only_ik: true